### ISSUE TITLE
Crash when placing a block in a label

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [MehVahdJukaar/labels-multi#1]
**MC** 1.19.2
**FAPI** 0.62.0
**Labels** 1.0

To reproduce:

1. Place a label on a side of a block
2. Right-click on it with any block, I used stone
3. Crash

Logs: https://gist.github.com/Footage2-Amply-Pounce/27841a04c3c32dfba3fd49e68ce300f8

**Comment by MehVahdJukaar** [comment]
Update moonlight. Real issue here is fabric mod JSON not being set correctly for dependencies, I'll fix that
