### ISSUE TITLE
Cant display the item name

### ISSUE THREAD

**Issue by playernik2003** [MehVahdJukaar/labels-multi#12]
So i am playing in 1.18.2 version 1.0 in fabric ans i cant let the label display the item name when using a feather on it.
Sorry if this doesn't belong here but i am unable to log into my curseforge account atm.

**Comment by MehVahdJukaar** [comment]
Only a feature of latest 1.19 version. Old ones ccan only do it globally with configs

**Comment by playernik2003** [comment]
> Only a feature of latest 1.19 version. Old ones ccan only do it globally with configs

Ah okay could you maybe explain it how i can get it to work via global config?

**Comment by MehVahdJukaar** [comment]
Open the config, edit it

**Comment by MehVahdJukaar** [comment]
Or use a config menu mod to do it ingame like every other mod

**Comment by playernik2003** [comment]
> Or use a config menu mod to do it ingame like every other mod

Then i have a new issue i cant open the config from inside of the game im using mod meni for it but it doesnt let me open the config

**Comment by MehVahdJukaar** [comment]
Mod menu does not add a config GUI. Cloth config or yacl do
