### ISSUE TITLE
Label floats off the surface..

### ISSUE THREAD

**Issue by tacogerbil** [MehVahdJukaar/labels-multi#24]

**Comment by MehVahdJukaar** [comment]
What does this even mean? Screenshots?

**Comment by tacogerbil** [comment]
Weird... Sorry about that.   When I was generating the other ticket, a
duplicate window popped up and I closed it (I thought it was a duplicate
because it had the subject already filled identical to the original at the
time).  Whatever I did must've opened a second ticket..  I sincerely
apologize.
