### ISSUE TITLE
Chest pins doesn't hide

### ISSUE THREAD

**Issue by DTech10** [MehVahdJukaar/labels-multi#30]
Ever since I moved from Optifine to [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium) this happens

![2023-08-06_12 53 58](https://github.com/MehVahdJukaar/labels-multi/assets/136813833/dd30c183-af49-479e-bb3b-d855e0c8c7ea)

**Comment by MehVahdJukaar** [comment]
This is not an issue. Labels don't alter cheats in any way

**Comment by DTech10** [comment]
huh, then what how do i hide the chest pins like this?
![image](https://github.com/MehVahdJukaar/labels-multi/assets/136813833/bf9eee19-6692-4c6f-ab17-905cd5b64bfa)
apparently its not bcus of Rubidium, and even Optifine the chest pins still blocking the label

**Comment by MehVahdJukaar** [comment]
Those chest are simply rotated

**Comment by DTech10** [comment]
oh. crap, aight imma close this issue
